version: "3"
services:
  jupyter:
    build: 
      context: ./pytorch
      args:
        - USERNAME=${NB_USER}
    #restart: unless-stopped
    container_name: mytorch  
    ports:
      - "${JUPYTER_PORT}:8888"
    user: ${NB_USER}
    volumes:
      - "./:/home/${NB_USER}/work"
    working_dir: /home/${NB_USER}/work/notebooks        
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: jupyter-notebook --NotebookApp.base_url=jupyter --NotebookApp.default_url=lab --ip 0.0.0.0 
