version: "3"
services:
  jupyter:
    build: ./pytorch
    #restart: unless-stopped
    container_name: mytorch  
    ports:
      - "8888:8888"
    user: your_user_name
    volumes:
      - "./:/home/${USERNAME}/work"
    working_dir: /home/${USERNAME}/work/notebooks        

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: jupyter-notebook -e JUPYTER_ENABLE_LAB=yes --NotebookApp.base_url=jupyter --NotebookApp.default_url=lab --ip 0.0.0.0 
